rza1_can: Fix compilation error due to missing device tree functions in kernel 4.4
drivers/net/can/rza1_can.c: In function ‘rz_can_probe’:
drivers/net/can/rza1_can.c:943:6: error: implicit declaration of function ‘of_property_read_variable_u32_array’ [-Werror=implicit-function-declaration]
  n = of_property_read_variable_u32_array(pdev->dev.of_node, "channels", channel, 0, sizeof(channel)/sizeof(channel[0]));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~